# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: python:3.11

include:
- template: Security/SAST.gitlab-ci.yml

stages:
  - lint
  - test
  - buld
  - package
  - release

before_script:
  - pip install poetry==1.5.1
  - poetry install -E adapters --no-interaction --no-ansi

lint-mypy:
  stage: lint
  script: make lint-mypy

sast:
  stage: test

