name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  unittests:
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]
    name: Unit Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: SanctumLabs/ci-workflows/.github/workflows/python-test.yml@main
    with:
      command: make test
      python-version: ${{ matrix.python-version }}
      packager: poetry